spring:
  cloud:
    gateway:
      routes:
        - id: profiles-principal
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/me, /api/v1/spendings/me, /api/v1/therapist-profiles/me, /api/v1/admin-profiles/me, /api/v1/profiles/me/drop-sober-date, /api/v1/calendar/**
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles, /api/v1/profiles/*/*, /api/v1/therapist-profiles/**, /api/v1/therapist-profiles, /api/v1/profiles/api-doc
            - Method=GET
        - id: profiles-therapist
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/set-client-step/**, /api/v1/profiles/*/execute-relapse, /api/v1/profiles/*/start-treatment, /api/v1/therapist-notes, /api/v1/therapist-notes/**, /api/v1/therapist-notes/search/**
            - Method=POST,GET,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - therapist-diar
        - id: profiles-admin
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/admin/**, /api/v1/admin-notes, /api/v1/admin-notes/**, /api/v1/admin-notes/search/**
            - Method=POST,GET,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - admin-diar
        - id: profiles-admin-therapist-read
          uri: http://profiles
          predicates:
            - Path=/api/v1/private/profiles/**
            - Method=GET
          metadata:
            auth-roles:
              - admin-diar
              - therapist-diar
        - id: gamification-manager-principal
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/commands/client/me/**
            - Method=POST,GET
          filters:
            - AddPrincipalToPathFilter
        - id: gamification-manager-web
          uri: http://gamification-manager-web
          predicates:
            - Path=/api/v1/web/**, /api/v1/gamification-manager-web/**
            - Method=GET
          filters:
            - AddPrincipalToPathFilter
        - id: gamification-manager-web-principal-post
          uri: http://gamification-manager-web
          predicates:
            - Path=/api/v1/web/commands/client/me/**
            - Method=POST
          filters:
            - AddPrincipalToPathFilter
        - id: gamification-manager-admin
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/cards/**, /api/v1/cards, /api/v1/tasks, /api/v1/tasks/**, /api/v1/categories/**, /api/v1/categories
            - Method=POST,PATCH,DELETE
          metadata:
            auth-roles:
              - admin-diar
        - id: gamification-manager-web-admin
          uri: http://gamification-manager-web
          predicates:
            - Path=/api/v1/web/cards/**, /api/v1/web/cards, /api/v1/web/tasks,  /api/v1/web/tasks/**, /api/v1/web/programs,  /api/v1/web/programs/**, /api/v1/web/admin/**
            - Method=POST,PATCH,DELETE
          metadata:
            auth-roles:
              - admin-diar
        - id: gamification-manager-web-therapist
          uri: http://gamification-manager-web
          predicates:
            - Path=/api/v1/web/therapist/**
            - Method=POST
          metadata:
            auth-roles:
              - therapist-diar
        - id: gamification-manager
          uri: http://gamification-manager
          predicates:
            - Path=/api/v1/cards/**, /api/v1/tasks/**, /api/v1/categories/**, /api/v1/gamification-manager/**, /api/v1/todo/**, /api/v1/task-executions/**
            - Method=GET
          filters:
            - AddPrincipalToPathFilter
        - id: keycloak-admin-adapter
          uri: http://keycloak-admin-adapter
          predicates:
            - Path=/api/v1/keycloak-admin-adapter/api-doc
            - Method=GET
          filters:
            - AddPrincipalToPathFilter
        - id: keycloak-admin-adapter-therapist-admin
          uri: http://keycloak-admin-adapter
          predicates:
            - Path=/api/v1/sso/**
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - admin-diar
        - id: achievements-admin
          uri: http://achievements-manager
          predicates:
            - Path=/api/v1/achievements/**, /api/v1/achievements-monthly/**, /api/v1/achievements-weekly/**, /api/v1/achievements-step, /api/v1/achievements-step/**, /api/v1/commands/*/set-achievement/**
            - Method=POST,PATCH,DELETE
          metadata:
            auth-roles:
              - admin-diar
              - therapist-diar
        - id: achievements-manager
          uri: http://achievements-manager
          predicates:
            - Path=/api/v1/achievements/**, /api/v1/achievements-monthly/**, /api/v1/achievements-weekly/**, /api/v1/achievements-scheduled/**, /api/v1/step-user/**, /api/v1/achievements-step/**, /api/v1/achievements-step, /api/v1/achievement-user/**, /api/v1/achievements-manager/api-doc
            - Method=GET
          filters:
            - AddPrincipalToPathFilter
        - id: statistics
          uri: http://statistics
          predicates:
            - Path=/api/v1/statistics/presence/**, /api/v1/statistics/api-doc
            - Method=GET
          filters:
            - AddPrincipalToPathFilter
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**, /api/v1/multimedia-manager/**
        - id: notification-service
          uri: http://notification-service
          predicates:
            - Path=/api/v1/notifications/me/device-token, /api/v1/notifications/push, /api/v1/emails, /api/v1/notification-service/api-doc
            - Method=POST,GET
          filters:
            - AddPrincipalToPathFilter
        - id: payments-manager
          uri: http://payments-manager
          predicates:
            - Path=/api/v1/notifications/nets, /api/v1/payments/**, /api/v1/payments-manager/api-doc
            - Method=POST,GET
          filters:
            - AddPrincipalToPathFilter
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc


keycloak-client:
  server-url: https://auth-dev.thehousehealth.com/auth
