server:
  port: 8081

security-constraints:
  open-uri:
    - /actuator/**
    - /api/v1/*/api-doc
    - /webjars/swagger-ui/**
    - /swagger-ui**
    - /v3/api-docs/**
    - /api/v1/notifications/nets

cors:
  allowedOrigins: "*"
  allowedMethods: "*"
  allowedHeaders: "*"
  allowedCredentials: true
  maxAge: "3600"

spring:
  cloud:
    gateway:
#      httpclient:
#        connect-timeout: 3000
#        response-timeout: 7s
      forwarded:
        enabled: true
      x-forwarded:
        enabled: true
        forEnabled: true
        protoEnabled: true
        portEnabled: true
        prefixEnabled: true
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
      routes:
        - id: profilesPrincipal
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/profiles/me, /api/v1/profiles/test
            - Method=GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: profiles
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/profiles/*/*, /api/v1/profiles/api-doc
        - id: openapi
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: ai-management
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/emotions/**,/api/v1/sleep,/api/v1/sleep/**
            - Method=GET,POST
        - id: health-data
          uri: http://localhost:9085
          predicates:
            - Path=/api/v1/users/me/hrv, /api/v1/users/me/steps, /api/v1/health-data/api-doc
            - Method=GET,POST
          filters:
            - AddPrincipalToPathFilter
        - id: gamification-manager
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/achievements/**, /api/v1/cards/**, /api/v1/posts/**, /api/v1/steps/**, /api/v1/tasks/**, /api/v1/gamification-manager/**
        - id: descriptions
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/*/*/description
            - Method=GET,PUT,PATCH
          filters:
            - RewritePath=/api/v1/(?<entity>.*)/(?<path>.*)/description, /api/v1/description//$\{path}/
        - id: keycloak-admin-adapter
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/sso/**
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - admin-diar
              - therapist-diar
        - id: keycloak-admin-adapter-openAPI
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/keycloak-admin-adapter/api-doc
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: web
            authorization-grant-type: authorization_code
            redirect-uri: ${keycloak-client.server-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
keycloak-client:
  server-url: http://auth.thehouserehab.com/
  realm: thehouse

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

springdoc:
  packages-to-scan: com.agenatech
  custom:
    ignored-routes:
      - achievements-admin
      - statistics-admin
      - profiles-principal
      - profiles-therapist
      - profiles-admin
      - profiles-admin-therapist-read
      - gamification-manager-principal
      - gamification-manager-admin
      - gamification-manager-web-admin
      - gamification-manager-web-therapist
      - gamification-manager-therapist
      - gamification-manager-web-principal-post
      - keycloak-admin-adapter-therapist-admin
      - keycloak-admin-adapter-principal
      - statistics-admin
      - openapi
      - descriptions
      - notification-service-principal

health:
  config:
    enabled: false

management:
  health:
    probes.enabled: true
