server:
  port: 8081
  forward-headers-strategy: framework
  connection-timeout: 5s
spring:
  data.rest.base-path: api/v1

  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/gamificaton-manager?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  cache:
    type: redis
    expiration:
      tasks-by-category-step:
        max-idle-time: 30000
        ttl: 0
      cards-by-task:
        max-idle-time: 30000
        ttl: 0
      recurring-tasks-by-step:
        max-idle-time: 30000
        ttl: 0
      tasks-executions-by-user-date:
        max-idle-time: 0
        ttl: 86400000
      tasks-executions-by-user:
        max-idle-time: 30000
        ttl: 0
      user-data:
        max-idle-time: 30000
        ttl: 0

  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"

  kafka:
    enabled: false
    bootstrap-servers: pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
    properties:
      security.protocol: SASL_SSL
      basic.auth.credentials.source: USER_INFO
      sasl:
        mechanism: PLAIN
    producer:
      bootstrap-servers: pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: reply:com.agenatech.gamificationmanager.model.ExecutedCard
    topic:
      name: card-reply
      replicas: 2
      partitions: 3
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: gamification-manager
      profiles-topic.name: user-profile
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: profile:com.agenatech.common.dto.UserProfile
        sasl:
          mechanism: PLAIN
        bootstrap.servers: pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
        security.protocol: SASL_SSL
        session.timeout.ms: 45000
        basic.auth.credentials.source: USER_INFO

management:
  health:
    show-details: always
    probes.enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

multimedia:
  url: http://multimedia-manager
  path: /api/v1/multimedia
  bulk-url: /api/v1/multimedia/bulk

program:
  archived-step: 100

springdoc.api-docs.path: /api/v1/gamification-manager/api-doc

logging:
  level:
    com.agenatech: DEBUG
    org.springframework.cache: TRACE
feign.client.config.default.loggerLevel: full

health:
  config:
    enabled: false
sentry:
  dsn: https://d2c258aaf0194406a4b684d5671b8f03@o1167145.ingest.sentry.io/6257927

events:
  card-reply:
    statistics:
      url: http://localhost:8078
      endpoints:
        executed-card: /api/v1/statistics/cards/executed
