server:
  port: 8989
spring:
  kafka:
    enabled: true
    bootstrap-servers: b-1.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094
    properties:
      security.protocol: SSL
    producer:
      bootstrap-servers: b-1.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: profile:com.agenatech.solutions.profiles.model.UserProfile
    topic:
      name: user-profile
      replicas: 2
      partitions: 3
    consumer:
      group-id: profiles
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      step-topic.name: step-update-request
      payment-topic.name: client-payments
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: payment:com.agenatech.solutions.profiles.client.kafka.consumer.payload.PaymentEventDto
        bootstrap.servers: b-1.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094, b-2.kafkaqa.238fcd.c2.kafka.eu-north-1.amazonaws.com:9094
        security.protocol: SSL
        session.timeout.ms: 45000

  datasource:
    url: jdbc:postgresql://database-qa-1.co7q08si9fnn.eu-north-1.rds.amazonaws.com:5432/profiles?ssl=false
    username: postgres
    password: '{cipher}a4e03ee319ea9826cc10fcc845a80efd6eae373cf657616d6f80c1e4bc505694acc70302e230452c15b7b215c3415261'
    hikari:
      maximum-pool-size: 5
      initial-pool-size: 1
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache.redisson:
          entity.expiration.max_idle_time: 604800000
          config: redisson-qa.yml

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      cache:
        use_second_level_cache: true
        factory_class: org.redisson.hibernate.RedissonRegionFactory
        redisson:
          fallback: true

  redis:
    ssl: true
    redisson:
      config: |
        masterSlaveServersConfig:
          retryAttempts: 3
          retryInterval: 1500
          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          masterAddress: "redis://qa-001.7rswex.0001.eun1.cache.amazonaws.com:6379"
          slaveAddresses:
            - "redis://qa-002.7rswex.0001.eun1.cache.amazonaws.com:6379"
            - "redis://qa-003.7rswex.0001.eun1.cache.amazonaws.com:6379"



notifications:
  url: http://notification-service

program:
  url: http://gamification-manager-web

calendly:
  organization-id: 9b1093f4-7238-45bb-82f1-cd7d3278bf04
  key: '{cipher}0d51e0bef2641c5e5be7a2bad3b29d4c9d8844de0587ab0b5b91d02428322ca905781969ff8397edc23a441a0f57803da968f0b05df1a338b82e33a94f96f31d137941ff7281ed6af6415ec3c48e2abb94518d200f2d63e28c48434497ea05b33eec4ac643897f3ea81adfaab8082667457fec4c3ad725de225d1fdcca93607021b1eaa112be909b6a615820597b20d3c95e33b79ed0c2ea1282030c491fed0efbd481471ffaeb6b854d2d73b8aceae7ef77c7f41946354484457933a3837914dac36db76a0eba72ef8ca238578a67f1e11ff63e4bb0f67c019de731d01d36fdd5b520c7751f5efb5a7dd25d532c5eb96a867228a1317c1fee712fec74918866e5172c5b95475db6c6863171be7a50f8481196afb4b773b7f535c59ec04a773989771950b01361d56e706bd46c50067e186be0fd68fddc3bcc2313fff4a88f392b57357140fa876715a238fbabf9d25c6a4638bd7c62c7153fb8e2976b121449cb865714b2096066dbb85a2d31861a90ae0e84679ed08151860b828adb4fe95d73f8cb6ecc0bec965da86fb795ef0d0e721a39818653b8d3660014b46f4695595945f63fc361d67ec0bda459efbdfef4dfa8f0a0d01d8e57105be1c09f17a4f0'
