server:
  forward-headers-strategy: framework
  port: 8989
  connection-timeout: 5s

spring:
  data.rest.base-path: api/v1
  cache:
    type: redis

  datasource:
    url: jdbc:postgresql://localhost:5432/profiles?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          redisson:
            entity.expiration.max_idle_time: 10000
            config: redisson-local.yml
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      cache:
        use_second_level_cache: true
        factory_class: org.redisson.hibernate.RedissonRegionFactory
        redisson:
          fallback: true

  # Producer properties
  kafka:
    enabled: false
    bootstrap-servers: pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
    producer:
      bootstrap-servers: pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: profile:com.agenatech.solutions.profiles.model.UserProfile
    topic:
      name: user-profile
      replicas: 3
      partitions: 3

calendly:
  key: test
  url: https://api.calendly.com
  organization-id: 3130a622-f686-4ce8-aed5-e2d59df9fd78
  organization: ${calendly.url}/organizations/${calendly.organization-id}
  events-list-url: scheduled_events
  event-types-url: event_types
  users-url: organization_memberships
  invitations-url: organizations/{organizationId}/invitations

notifications:
  url: http://notification-service
  email-url: /api/v1/emails/relapse

program:
  url: http://localhost:9897
  users-program-data-url: /api/v1/web/user-program-data/search/by-ids
  user-program-data-url: /api/v1/web/user-program-data/search/by-id
  user-program-data-basic-url: /api/v1/web/user-program-data/{id}
  assign-program-url: /api/v1/web/admin/assign-program

management:
  health:
    show-details: always
    probes.enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

springdoc.api-docs.path: /api/v1/profiles/api-doc

logging:
  level:
    com.agenatech: DEBUG
feign.client.config.default.loggerLevel: full

health:
  config:
    enabled: false

sentry:
  dsn: https://d2c258aaf0194406a4b684d5671b8f03@o1167145.ingest.sentry.io/6257927





