server:
  port: 8078
  connection-timeout: 10s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/statistics-manager?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  cache:
    type: redis
    expiration:
      daily-presense:
        max-idle-time: 35000
        ttl: 0
      between-dates-presence:
        max-idle-time: 30000
        ttl: 0
      by-year-presence:
        max-idle-time: 20000
        ttl: 0
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"

  kafka:
    enabled: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      executed-card-topic:
        name: card-reply
        group-id: cards-execution-statistics
      profiles-topic:
        name: user-profile
        group-id: statistics
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: reply:com.agenatech.statistics.model.ExecutedCard
        sasl:
          mechanism: PLAIN
        bootstrap.servers: pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
        security.protocol: SASL_SSL
        session.timeout.ms: 45000
        basic.auth.credentials.source: USER_INFO

management.endpoints.web.exposure.include: '*'

springdoc.api-docs.path: /api/v1/statistics/api-doc

sentry:
  dsn: https://d2c258aaf0194406a4b684d5671b8f03@o1167145.ingest.sentry.io/6257927

logging:
  level:
    com.agenatech: DEBUG
    org.springframework.cache: TRACE

health:
  config:
    enabled: false



