spring:
  kafka:
    enabled: false
nets:
  checkout-url: https://client-portal-qa.thehousehealth.com/onboarding

events:
  client-payments:
    profiles:
      url: http://profiles
      endpoints:
        status: /api/v1/profiles/payment-status
